spring:
  application:
    name: coindesk-api-v1
  flyway:
    locations: classpath:db/migration/default
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none 
  h2:
    console:
      enabled: true
      path: /h2-console
server:  
  port: 8061
  servlet:
    context-path: /api/coindesk/v1
management:
  endpoints:
    health:
      show-details: always
    web: 
      exposure:
        include: health,info,metrics,prometheus,httptrace,loggers
        exclude: env,beans    
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      "service.name": ${spring.application.name}
  # otlp:
  #   tracing:
  #     endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 5s
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always        
info:
  git:
    location: 'classpath:git.properties'
springdoc:
  api-docs:
    enabled: true
#    path: /api-docs
  swagger-ui:
    enabled: true
#    path: /docs
    use-root-path: true
    disable-swagger-default-url: true
    display-request-duration: true
    operationsSorter: method
    tagsSorter: alpha
    oauth:
      clientId: edge-service
      clientSecret: rocking-secret
      use-basic-authentication-with-access-code-grant: true
  cache:
    disabled: false            