name: scs-101 commons ci

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
    branches:
      - main
      - feature/03-new_api
  pull_request:
    branches:
      - main
      - feature/03-new_api

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i 's|</project>|<distributionManagement><repository><id>github</id><name>GitHub</name><url>https://maven.pkg.github.com/fang2272/coindesk-api-v1</url></repository></distributionManagement></project>|g' pom.xml ;
          mvn  deploy